name: Testo Siniestro
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo -e "${{ secrets.PRIVATE_KEY }}" > identityfile 
      - run: cat identityfile
      - run: ssh root@${{ secrets.SERVER_DOMAIN }} -i ./identityfile "ls -la"

