name: Deploy To Staging
run-name: Process of Deployment
on:
  push:
    branches:
      - staging
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - name : hellou world
        run: echo hello world    

